name: Bug report
description: File a bug report
title: "[bug] <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug!
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Clear, concise description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screens / Context
