name: Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install Angular CLI
        run: npm i -g @angular/cli@19

      - name: Install dependencies
        working-directory: web
        run: npm ci || npm i

      - name: Lint
        working-directory: web
        run: npm run lint --if-present

      - name: Build
        working-directory: web
        run: npm run build --if-present
